### ISSUE TITLE
glb format help

### ISSUE THREAD

**Issue by GodGotzi** [asny/three-d-asset#21]
I am working on a simple 3d printer slicing software. I found a strange bug, atleast I don't understand it.

Probem: 
So I have a STEP file from my 3d-print bed that I wanted to load into my application, first I used this online converter
https://imagetostl.com/convert/file/step/to/glb to convert it to a glb file format.
Here is what it looks like in my application:
![image](https://github.com/asny/three-d-asset/assets/95647640/e7b2c662-d3b8-426f-92d9-139d1f7a092e)

This worked fine so at first I was satisfied, later that day I wanted to see some textures and used https://www.opencascade.com/products/cad-assistant/ to convert my STEP file to a proper GLB.
Exporting worked fine and I can reopen it within cad-assistant with textures and everything.
In cad-assistant view:
![image](https://github.com/asny/three-d-asset/assets/95647640/e9da32e8-caae-4dfe-a244-8e7f3dcbfa93)

Next I tried to load my GLB into my application, but I see nothing. At some point I saw a broken mesh in my 3d view that could mean something went wrong at deserialization
![image](https://github.com/asny/three-d-asset/assets/95647640/623b0267-62e7-4b17-ac43-ad0cf5bb8acf)

I thought there are several different version of GLB, cad-assistant just detects them and chooses the correct deserialization

```rust
let mut assets = three_d_asset::io::load(&["assets/bed3.glb"]).unwrap();
let cpu_model: CpuModel = assets.deserialize("bed3.glb").unwrap();

let mut model = Model::<PhysicalMaterial>::new(&context, &cpu_model)
    .unwrap()
    .remove(0);

let scale = Mat4::from_scale(1.0);
let rotation = Mat4::from_angle_y(degrees(90.0))
    .concat(&Mat4::from_angle_x(degrees(90.0)))
    .concat(&Mat4::from_angle_z(degrees(45.0)));

let translation = Mat4::from_translation(vec3(0.0, 0.0, 0.0));
model.set_transformation(translation * rotation * scale);
.
.
.
model.render(&camera, &[&light0, &light1]);
```
[objects.zip](https://github.com/asny/three-d-asset/files/12250214/objects.zip)

When I try todo the same thing with obj files it says
![image](https://github.com/asny/three-d-asset/assets/95647640/cf230be1-d502-4aa1-aa80-e734c7364a42)

Edit: My GLB doesn't work with the pbr example too, so its a GLB intern problem. Anything I export from blender as glb has the same problem.

Enviroment
Windows 10
winit

**Comment by asny** [comment]
Well, it's hardly surprising that something went wrong when converting a STEP file to a GLB with some online tool, I would actually be more surprised if it actually worked 😆 But anyway, it's really hard for me to say what's wrong, it could be in a lot of places, but probably it's the conversion that produces some bad data. I guess you just need to debug it 🤷 Maybe try to rule out everything else to make sure that the problem is the conversion. 

The obj problem is definitely just bad data, it's missing a field in the mtl file as described in the error.

Also, `three-d-asset` uses dependencies for parsing, so the [wavefront_obj](https://crates.io/crates/wavefront_obj) crate for parsing obj and the [gltf](https://crates.io/crates/gltf) crate for parsing glb/gltf, so you have to make issues in those crates if there's actually something that needs to be fixed.
